### ISSUE TITLE
about the performance reported in the benchmark

### ISSUE THREAD

**Issue by zhangzilongc** [M-3LAB/IM-IAD#1]
I want to know the benchmark's details (like test codes). I found the performance of Patchcore in VisA was different from the original paper of VisA. The performance of PatchCore is 92.4% (I-AUROC) in Table 6 of the original paper (SPot-the-Difference Self-Supervised Pre-training for Anomaly Detection and Segmentation). But the result in your benchmark is 95.1%. The gap is nearly 3%.

**Comment by jiaq-liu** [comment]
We used the official version of PatchCore to reproduce the results, set the image size and crop size to 256, and kept other parameters unchanged. Please refer to https://github.com/amazon-science/patchcore-inspection
